### ISSUE TITLE
StringIndexOutOfBoundsException in ErrorFormatter 

### ISSUE THREAD

**Issue by JuPfu** [JuPfu/chelona#1]
Converting base.ttl file with single unterminated triple statement results in stack trace.
This is a duplicate of issue https://github.com/sirthias/parboiled2/issues/138

File base.ttl:
     <#green-goblin> a <#comic-hero>

Convert: base.ttl
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 33
    at java.lang.String.substring(String.java:1950)
    at org.parboiled2.ParserInput$StringBasedParserInput.sliceString(ParserInput.scala:98)
    at org.parboiled2.ErrorFormatter.formatProblem(ErrorFormatter.scala:80)
    at org.parboiled2.ErrorFormatter.format(ErrorFormatter.scala:58)
    at org.parboiled2.ErrorFormatter.format(ErrorFormatter.scala:51)
    at org.parboiled2.Parser.formatError(Parser.scala:105)
    at org.chelona.Main$.delayedEndpoint$org$chelona$Main$1(Main.scala:81)
    at org.chelona.Main$delayedInit$body.apply(Main.scala:27)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at org.chelona.Main$.main(Main.scala:27)
    at org.chelona.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 1

**Comment by JuPfu** [comment]
Solved with update of Parboiled2.
